runtime: python312
instance_class: F1

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_throughput_utilization: 0.5
  max_concurrent_requests: 20
  max_pending_latency: 30ms

handlers:
  # Handle all requests with the Flask application
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301